name: cindyl
favicon: null
layout_spectrum: 0.6646123910322785
typography_spectrum: 0.6524295650888234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8567787383217365
  lightness: 0.8624047990888357
  saturation: 0.8053875144105405
  rhythmicContrast: 0.8422164774965495
purpose: []
