name: cindyl
favicon: null
layout_spectrum: 0
typography_spectrum: 0.37803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a285a3'
    - '#606582'
    - '#c1c3ce'
    - '#a6a8b6'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
