name: cindyl
favicon: null
layout_spectrum: 0
typography_spectrum: 0.37803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e1d8'
    - '#35182c'
    - '#986d76'
    - '#cbbeb6'
    - '#764d5d'
  brandStrength: 0.875
  lightness: 0.8624047990888357
  saturation: 0.8053875144105405
  rhythmicContrast: 0.8422164774965495
purpose: []
